version: '3.8'

services:
  ui:
    build:
      context: ./UI
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - EEP1_URL=http://eep1:5000
    volumes:
      - ./UI/instance:/app/instance
    depends_on:
      - eep1
    networks:
      - app-network

  eep1:
    build:
      context: ./EEP1
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - IEP1_URL=http://iep1:5001
      - IEP2_URL=http://iep2:5004
      - STORAGE_DIR=/app/storage
    volumes:
      - eep1_storage:/app/storage
      - eep1_persistence:/app/persistence
    depends_on:
      - iep1
      - iep2
    networks:
      - app-network

  iep1:
    build:
      context: ./IEP1
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - iep1_storage:/app/storage
    networks:
      - app-network

  iep2:
    build:
      context: ./IEP2
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-claude-3-7-sonnet-20250219}
    volumes:
      - iep2_storage:/app/storage
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  eep1_storage:
  eep1_persistence:
  iep1_storage:
  iep2_storage:
