version: '3.8'

services:
  ui:
    build:
      context: ./UI
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - EEP1_URL=http://eep1:5000
      - AUTH_SERVICE_URL=http://auth-service:5004
    depends_on:
      - eep1
      - auth-service
    networks:
      - app-network

  eep1:
    build:
      context: ./EEP1
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - IEP1_URL=http://iep1:5001
      - STORAGE_DIR=/app/data
    volumes:
      - ./EEP1/data:/app/data
    depends_on:
      - iep1
    networks:
      - app-network

  iep1:
    build:
      context: ./IEP1
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./IEP1/data:/app/data
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  schedule_storage:
  eep1_storage:
