version: '3.8'

services:
  ui:
    build:
      context: ./UI
      dockerfile: Dockerfile.ui
    ports:
      - "3002:3000"
    depends_on:
      - eep1
      - auth-service
    networks:
      - app-network

  eep1:
    build:
      context: ./EEP1
      dockerfile: Dockerfile.eep1
    ports:
      - "5000:5000"
    environment:
      - IEP1_URL=http://iep1:5001
    env_file:
      - ./IEP1/.env
    volumes:
      - ./EEP1/storage:/app/storage
    depends_on:
      - iep1
    networks:
      - app-network

  iep1:
    build:
      context: ./IEP1
      dockerfile: Dockerfile.iep1
    ports:
      - "5001:5001"
    env_file:
      - ./IEP1/.env
    volumes:
      - schedule_storage:/app/storage
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile.auth
    ports:
      - "5004:5004"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/lock-in-scheduler
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  schedule_storage:
  eep1_storage:
